version: '3.1'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./db:/var/lib/mysql"
    networks:
      - dorna-network
  dorna-server:
    container_name: dorna-app
    build:
      context: .
      dockerfile: Dockerfile
    image: dorna-app:latest
    ports:
      - "18888:8888"
    expose:
      - "18888"
    networks:
      - dorna-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
volumes:
  my-db:
networks:
  dorna-network:
    driver: bridge