version: '3.6'

services:
  dorna-server:
    container_name: dorna-app
    build:
      context: .
      dockerfile: Dockerfile
    image: dorna-app:latest
    ports:
      - "18888:8080"
    expose:
      - "18888"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: dornadbuser
      MYSQL_PASSWORD: dornadbpass
      MYSQL_PORT: 3306


  db:
    container_name: mysqldb
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=springit
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - "./db:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
volumes:
  my-db: